### ISSUE TITLE
Failed to Parse Magnet Link

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#255]
18-3-21 12:59:11.7|Info|NzbSearchService|Searching 5 indexers for [Sufjan Stevens - Carrie & Lowell (2015)]
18-3-21 12:59:19.6|Info|DownloadDecisionMaker|Processing 25 releases
18-3-21 12:59:37.7|Error|QBittorrent|Failed to parse magnetlink for release 'Sufjan Stevens - Carrie & Lowell (2015) {FLAC} vtwin88cube': 'magnet:?xt=urn:btih:c837be23926b61700db88c5648b1af5339d17c80&dn=Sufjan Stevens - Carrie & Lowell (2015) {FLAC} vtwin88cube.torrent'

[v0.2.0.316] System.FormatException: A field-value pair of the magnet link contain more than one equal'.
   at MonoTorrent.MagnetLink.ParseMagnetLink(String url) in C:\projects\lidarr\src\MonoTorrent\MagnetLink.cs:line 50
   at MonoTorrent.MagnetLink..ctor(String url) in C:\projects\lidarr\src\MonoTorrent\MagnetLink.cs:line 32
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteAlbum remoteAlbum, String magnetUrl) in C:\projects\lidarr\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 208

18-3-21 12:59:37.7|Info|DownloadService|Report sent to qBT. Sufjan Stevens - Carrie & Lowell (2015) {FLAC} vtwin88cube

On windows. Latest release.

**Comment by Qstick** [comment]
What indexer do you have setup in Lidarr?

**Comment by bobloadmire** [comment]
https://i.imgur.com/3ubPDn8.png

**Comment by Qstick** [comment]
The url that’s being received from indexer is not url encoded, thus its invalid. That why I’d like to know which of your indexers it came from.

**Comment by bobloadmire** [comment]
hmm yeah not sure how to know which indexer of those it is.

**Comment by bobloadmire** [comment]
did a manual search and it threw the error again snatching it from Torrentz2

**Comment by Qstick** [comment]
Yea, i was going to say just turn your logging to trace, but that works as well. I presume you have Torrentz2 setup thru Jackett?

**Comment by bobloadmire** [comment]
correct

**Comment by Qstick** [comment]
Fixed with https://github.com/Jackett/Jackett/commit/021468d6f5d6ba9d680ab38c23637fbfc39bb3a2

**Comment by bobloadmire** [comment]
Excellent, thanks, so we just have to wait for a jackett release

**Comment by leha007** [comment]
Issues still exist:
Message
{Failed to parse magnetlink for release 'Arctic Monkeys - Tranquility Base Hotel & Casino (2018) Mp3 (320 kbps) [Hunter]': 'magnet:?xt=urn:btih:5AC3D859E9F6A9DAF341D48A58FD96D963359A5A&dn=Arctic+Monkeys+-+Tranquility+Base+Hotel+&+Casino+(2018)+Mp3+(320+kbps)+[Hunter]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://tracker.cypherpunks.ru:6969/announce&tr=udp://inferno.demonoid.pw:3418/announce&tr=udp://thetracker.org:80/announce&tr=udp://thetracker.org:80/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://pubt.in:2710/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.}

Exception
System.FormatException: A field-value pair of the magnet link contain more than one equal'.
at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x00071] in :0
at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in :0
at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteAlbum remoteAlbum, System.String magnetUrl) [0x00004] in :0

Using Lidarr (I know it's radarr repo but still feels the same problem)
Using latest Jackett - {Linuxserver.io version:- v0.13.625-ls56 Build-date:- 2020-03-12T06:14:51+00:00}
