### ISSUE TITLE
Stuck after rescan

### ISSUE THREAD

**Issue by Gandrushka** [Lidarr/Lidarr#3734]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After the folder rescan lidarr just stucks. 

I tried to turn on/off:
- metadata sync
- metadata write only on import
- metadata write off
- fingerprinting on new downloads
- fingerprinting all files

### Expected Behavior

After the refresh, lidarr is not being stuck and i don't need to restart it

### Steps To Reproduce

1. Start lidarr
2. See "rescan folders" tasks (on multiple instances)
![image](https://github.com/Lidarr/Lidarr/assets/8702209/2afee397-8539-46d3-a5d2-8f55e4628981)
3. Lidarr stucks
4. Close lidarr via tray
5. Close lidarr via Windows task manager

### Environment

```markdown
- OS: Windows 10
- Lidarr: 1.2.0.3183
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Microsoft Edge / Google Chrome
- Database:Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

2023-05-26 19:31:34.2|Error|RemotePathMappingCheck|Unknown error occured in RemotePathMapping HealthCheck

[v1.2.0.3183] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 389
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.GetApiVersion(QBittorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 76
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetStatus() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 363
   at NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\RemotePathMappingCheck.cs:line 63

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by misleadingrhino** [comment]
Having the same issue with 

- OS: Ubuntu 20.04
- Lidarr: 1.2.2.3242
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox
- Database: Sqlite 3.40.1

**Comment by Qstick** [comment]
Essentially connection to your qBit client is timing out here. You should fix that.

**Comment by jackmaninov** [comment]
Started from a fresh config and db, let it rebuild overnight and am still seeing the same RemotePathMapping HealthCheck errors.

**Comment by jackmaninov** [comment]
> Essentially connection to your qBit client is timing out here. You should fix that.

@Qstick looks to me like clients are timed out after being DOS'ed by lidarr, but I don't see anything causing the RemotePathMapping HealthCheck spam.

**Comment by Qstick** [comment]
Thanks for digging in a bit more it's helpful, we'll take a look

**Comment by jackmaninov** [comment]
I'm no longer seeing this issue on 1.2.5.3288, but I can no longer test with my old database from when I was getting the errors (got corrupted somehow). 

Can anyone else confirm the error occurs after upgrading to 1.2.5.3288?

**Comment by mikeyounge** [comment]
I am also experiencing this behavior with SabNZB.

```
[v1.3.1.3371] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Lidarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Lidarr.Common/Http/HttpClient.cs:line 141
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 202
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetConfig(SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 89
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetStatus() in ./Lidarr.Core/Download/Clients/Sabnzbd/Sabnzbd.cs:line 246
   at NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck.Check() in ./Lidarr.Core/HealthCheck/Checks/RemotePathMappingCheck.cs:line 63
[Error] RemotePathMappingCheck: Unknown error occured in RemotePathMapping HealthCheck 
```

I do not know if it ever recovers. I have been restarting the container when I experience it. Since discovering this thread, I will let it run and see if comes back. Http access is gone during this error loop.

**Comment by alex3305** [comment]
I have the same issue with SABnzbd. It has started for me since I migrated to a new (and way faster) machine. I also notice that Lidarr and the download client can get out of sync pretty easily. And after letting Lidarr do it's thing with outputting all the Exceptions, http access returns and everything seems fine.

My environment:

- OS: unRAID 6.12
- Lidarr: 1.3.1.3371
- Docker Install: yes (linuxserver.io)
- Using Reverse Proxy: no (doesn't make a difference)
- Browser: Google Chrome
- Database:Sqlite 3.41.2

**Comment by Simpuhl** [comment]
I am also having this issue

**Comment by Majawat** [comment]
I am also having this issue all of a sudden.

- Version: 1.2.6.3313
- Package Version: 1.2.6.3313-ls133 by linuxserver.io
- .NET: Yes (6.0.16)
- DB Migration: 69
- Database: Sqlite 3.41.2
- OS: unRAID
- Docker: Yes
- Using Reverse Proxy: Yes

**Comment by alex3305** [comment]
@Majawat @Simpuhl (and others) Could you perhaps also share your systems specs? You can edit your post. Because I'm wondering if it's performance related.

My system specs:
- Intel Core i5 13500 (using 2 P-cores for Lidarr)
- Lidarr data is stored on a Samsung 980 SSD
- Music is stored in a 2TB Transcend SSD

For networking I have tried using FQDN's with a reverse proxy (Nginx Proxy Manager), using hostnames or IP addresses. In all of these setups both sending and processing downloads work but also this issue arises. 

Also my SABnzbd config (for completeness):

```
Name:               SABnzbd
Active:             Yes
Host:               sabnzbd.lan
Port:               8080
Use SSL:            no
API key:            [REDACTED]
Username:           n/a
Password:           n/a
Category:           audio
Recent Priority:    Default
Older Priority:     Default

Remove Completed:   no
Remove Failed:      no
```

**Comment by Simpuhl** [comment]
Did you by chance implement unlackarr? That's the only thing that changed for me. It checks and unpacks zipped files

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alex3305** [comment]
> Did you by chance implement unlackarr?

No. I don't even know what that is tbh. And I think you mean _unpackarr_? Besides stock Lidarr and SABnzbd I only use the [flac2mp3 Docker mod](https://github.com/TheCaptain989/lidarr-flac2mp3).

**Comment by Simpuhl** [comment]
Yes sorry. Damn typo. I meant unpackarr

**Comment by Mnikley** [comment]
problem persists as of 1.2.6.3313.
Started first noticing the bug after:
- adding a second download client (added sabnzbd in addition to qbittorrent)
- using gluetun for both download services
- both download services share the same folder for completed downloads

disabling completed download handling resolves the problem

**Comment by Simpuhl** [comment]
I am getting this error every 10 minutes or so now... I keep having to force restart Lidarr just to use it. I've already reinstalled from scratch and the issue returned after a few days.

https://i.imgur.com/kZDgfIz.png

**Comment by alex3305** [comment]
@Simpuhl AFAIK force restarting Lidarr worsens this behavior as Lidarr will rescan the music library on restarts.

---

Adding the SABnzbd logging as it's little different from the QBittorrent logging posted above:

```
[Error] RemotePathMappingCheck: Unknown error occured in RemotePathMapping HealthCheck 

[v1.3.5.3530] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Lidarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Lidarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 202
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetConfig(SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 89
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetStatus() in ./Lidarr.Core/Download/Clients/Sabnzbd/Sabnzbd.cs:line 246
   at NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck.Check() in ./Lidarr.Core/HealthCheck/Checks/RemotePathMappingCheck.cs:line 63
```

I see the above exception 745 times in my logging since the last full scan, while

```
[Warn] DownloadMonitoringService: Unable to retrieve queue and history items from SABnzbd 
```

only shows up once. However this is exactly in the middle after 373 errors.

**Comment by xaviergxf** [comment]
This could be a port exhaustion problem. The current dotnet versions have eaten all important information that would help analyze this issue, fortunately this seems fixed in .net 8 [https://github.com/dotnet/runtime/issues/84712](https://github.com/dotnet/runtime/issues/84712)

**Comment by jackmaninov** [comment]
> This could be a port exhaustion problem. 
Yes, I expect the "unknown" error is as a result of port exhaustion. However, at least in my case the issue seems to be lidarr voluntarily causing that port exhaustion to happen by flooding our download clients with health checks. 

If anyone here had dinner experience and is able to build from source, maybe they could put in some trace logging to figure out why so many healthchecks are launched.

**Comment by jorti** [comment]
I'm having the same problem here all the time. I'm using 2 download clients, Transmission and SABnzbd:

```
[Error] RemotePathMappingCheck: Unknown error occured in RemotePathMapping HealthCheck 

[v1.3.5.3530] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Lidarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Lidarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 202
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetConfig(SabnzbdSettings settings) in ./Lidarr.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs:line 89
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetStatus() in ./Lidarr.Core/Download/Clients/Sabnzbd/Sabnzbd.cs:line 246
   at NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck.Check() in ./Lidarr.Core/HealthCheck/Checks/RemotePathMappingCheck.cs:line 63


[Error] RemotePathMappingCheck: Unknown error occured in RemotePathMapping HealthCheck 

[v1.3.5.3530] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Lidarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Lidarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Lidarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in ./Lidarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 316
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetConfig(TransmissionSettings settings) in ./Lidarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 120
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetStatus() in ./Lidarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 175
   at NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck.Check() in ./Lidarr.Core/HealthCheck/Checks/RemotePathMappingCheck.cs:line 63
```

**Comment by Simpuhl** [comment]
It's definitely fixed for me, I'm on the latest nightly

**Comment by B0PE** [comment]
My program no longer gets stuck after the scan, but the memory usage still jumps to 7-8GB.
