### ISSUE TITLE
synology fpcalc could not be found - chromaprint installed

### ISSUE THREAD

**Issue by adispi** [lidarr/Lidarr#746]
**Describe the bug**
error on system:
fpcalc could not be found. Audio fingerprinting disabled.
chromaprint 1.4.3 is installed (fpcalc version 1.4.3).

Version 0.6.0.815
Mono Version 5.18.0.240
DB Migration 29
Mode  Console

synology dsm 6.2.2

tried to copy the fpcalc to the lidarr dir, cannot find config to set fpcalc path.

**Comment by ta264** [comment]
Please join the discord support channel and we can try to figure it out.

https://discord.gg/8Y7rDc9

**Comment by adispi** [comment]
issue resolved by creating link to the fpcalc in /usr/local/bin:
cd /usr/local/bin/
sudo ln -s /volume1/@appstore/chromaprint/bin/fpcalc .
and restart lidarr

**Comment by mattgrah-am** [comment]
@adispi - This works, thank you!

**Comment by triksmelb** [comment]
@adispi - creating symlink did not fix the issue on Synology 1813+ when following your instructions:

1. logged in via SSH
2. navigated to: cd /usr/local/bin/
3. created symlink: sudo ln -s /volume1/@appstore/chromaprint/bin/fpcalc
4. restarted Lidarr from package centre
5. logged back into Lidarr but same error - fpcalc could not be found. Audio fingerprinting disabled.
6. check symlink is created: sudo ln -s /volume1/@appstore/chromaprint/bin/fpcalc
ln: failed to create symbolic link ‘./fpcalc’: File exists

Is there an additional file or something that needs to be copied/installed?

**Comment by ta264** [comment]
You need to make sure `fpcalc` is on the `PATH` for the user running lidarr. If you need more assistance please ask in the discord support channel.

**Comment by ta264** [comment]
PS this is really an issue with the Synology chromaprint package - it really ought to be adding it's binaries to `PATH`

**Comment by adispi** [comment]
opened a bug to synocommunity:
https://github.com/SynoCommunity/spksrc/issues/3687

**Comment by ta264** [comment]
Thanks

**Comment by I3ezirkFuhrer** [comment]
Thank you for linking! Confirmed working on DS1817+.

**Comment by BenjV** [comment]
This is just a faulty design of lidarr.
If a external binary is needed then lidarr should have a configuration item somewhere so it can be told where to find it.
Relying on a PATH environment variable is very old school and outdated and is designed for commandline use and not for gui applications.

**Comment by SyrinTV** [comment]
> 
> 
> issue resolved by creating link to the fpcalc in /usr/local/bin:
> cd /usr/local/bin/
> sudo ln -s /volume1/@appstore/chromaprint/bin/fpcalc .
> and restart lidarr

It is now asking for a password, not sure how to proceed. Thanks

**Comment by ta264** [comment]
It wants your Synology root password (`sudo` means run the command as root)

**Comment by ta264** [comment]
But the Synology packages are fairly broken and the maintainers unhelpful so you're probably better off using a docker container if that's an option

**Comment by gitthangbaby** [comment]
Works just by installing the package

**Comment by gitthangbaby** [comment]
works without any fix on 6.2, SynoCommunity OK, cphub KO

**Comment by rdyson** [comment]
> works without any fix on 6.2, SynoCommunity OK, cphub KO

Confirmed here too
