### ISSUE TITLE
Double-Artist album (aka split) handling

### ISSUE THREAD

**Issue by kimpenhaus** [lidarr/Lidarr#792]
Hi all,

I am new to Lidarr (swapping over from Headphones) and this is more a question than a bug report.

My library is consisting mostly out of Hardcore/Punk music and I am not pretty sure if this is somewhat special to that kind of music (never was into different stuff). There are so called split albums which contain tracks from 2 different artists. They are not handeld/called as various artists albums. (e.g.: https://musicbrainz.org/release-group/a0868611-5c89-3b1a-a29d-57278a80bb7e a split from $wingin' Utter$ and Youth Brigade).

Musicbrainz shows them like that:

![Bildschirmfoto 2019-04-28 um 08 44 56](https://user-images.githubusercontent.com/575109/56860871-71b44e00-699b-11e9-8a6d-a3b78b271cb7.png)

<img width="1089" alt="Bildschirmfoto 2019-04-28 um 08 45 14" src="https://user-images.githubusercontent.com/575109/56860877-7c6ee300-699b-11e9-8301-7c024ec55809.png">

My library was build/managed by the famous [beets](https://github.com/beetbox/beets) library manager and I actually want to keep it, because of the feature richness that tool provides.

Now to the problem I am facing:

beets is importing those split albums into a folder like `$wingin’ Utter$ _ Youth Brigade` - as a side node my folder name template is like `{Artist Name}/{Release Year} - {Album Title}` - because this is a multi artist release. The album is not putten under one of those artists nor both of them.

<img width="862" alt="Bildschirmfoto 2019-04-28 um 08 46 30" src="https://user-images.githubusercontent.com/575109/56860883-94466700-699b-11e9-910f-a2c48afec285.png">

and a query inside beets shows which tracks are from what artist:

<img width="758" alt="Bildschirmfoto 2019-04-28 um 08 52 04" src="https://user-images.githubusercontent.com/575109/56860892-b213cc00-699b-11e9-8342-de1cc6d7a6fb.png">

<img width="734" alt="Bildschirmfoto 2019-04-28 um 08 47 21" src="https://user-images.githubusercontent.com/575109/56860891-af18db80-699b-11e9-95e5-43e05b7a6e67.png">

Now when it comes to importing those albums into Lidarr I just saw that they are putten under just one artist - in the given example it's under $wingin' Utters but not under Youth Brigade:

![Bildschirmfoto 2019-04-28 um 08 43 59](https://user-images.githubusercontent.com/575109/56860911-e4bdc480-699b-11e9-832d-a837fca54721.png)

Youth Brigade doesn't have any sign they ever contributed to that album.

<img width="1151" alt="Bildschirmfoto 2019-04-28 um 08 44 31" src="https://user-images.githubusercontent.com/575109/56860913-eedfc300-699b-11e9-8705-ceb8a9ca34da.png">

Trying to import the mixed folder, as it was created from beets, is not an allowed while it is disabled

<img width="1558" alt="Bildschirmfoto 2019-04-28 um 08 46 00" src="https://user-images.githubusercontent.com/575109/56868818-e4531700-69f7-11e9-8f1b-c2db4ffae51c.png">

So my question is: What are my options? Is there any chance to get those albums imported withou changing the file-structure? My library is quite huge and was build over couple of years with lot's of time to get everything tagged quite nice. I don't want to change much on that side... I think I do know the answer 😞 

Sorry for quite a lot of pictures - I just putten them here to visualize the problem I have.

Thanks, m.

**Comment by ta264** [comment]
This should be possible in the next release I think (hopefully summer) but not a lot you can do til then. At the moment lidarr needs files to be in the correct artist directory, and from lidarr's point of view the artist is the first album artist. So lidarr needs the tracks in the winging utter folder at the moment.

**Comment by kimpenhaus** [comment]
Sounds good - I am not in a rush :+1:

**Comment by iAmRenzo** [comment]
<img width="895" alt="Schermafbeelding 2019-07-06 om 12 48 24" src="https://user-images.githubusercontent.com/1183790/60755187-5a718c80-9fec-11e9-83bc-af0d025def81.png">
I guess it's the same as this?
I have a lot of this, trying to organise them but I should wait....?! :)

**Comment by Cantello** [comment]
> <img alt="Schermafbeelding 2019-07-06 om 12 48 24" width="895" src="https://user-images.githubusercontent.com/1183790/60755187-5a718c80-9fec-11e9-83bc-af0d025def81.png">
> I guess it's the same as this? I have a lot of this, trying to organise them but I should wait....?! :)

The difference appears to be the so-called 'join phrase' ("&" vs. "/") but otherwise I think it is the same, according to https://musicbrainz.org/doc/Artist_Credits.

**Comment by iAmRenzo** [comment]
> > <img alt="Schermafbeelding 2019-07-06 om 12 48 24" width="895" src="https://user-images.githubusercontent.com/1183790/60755187-5a718c80-9fec-11e9-83bc-af0d025def81.png">
> > I guess it's the same as this? I have a lot of this, trying to organise them but I should wait....?! :)
> 
> The difference appears to be the so-called 'join phrase' ("&" vs. "/") but otherwise I think it is the same, according to https://musicbrainz.org/doc/Artist_Credits.

And is there already a solution for this?
Because, the title "Out to Sea" isn't showing under Tom Misch alone nor Carmody. And there are a lot of these...

**Comment by Cantello** [comment]
> And is there already a solution for this?
> Because, the title "Out to Sea" isn't showing under Tom Misch alone nor Carmody. And there are a lot of these...

That is most probably because the release type in MB is set to 'Unspecified', which lidarr cannot import. The easiest way to rectify this is to edit the release on musicbrainz to 'Album' (or whatever it is), wait for an hour for the results to filter through to lidarr and then refresh and add the album.

![image](https://user-images.githubusercontent.com/594700/70051807-2669ba00-15d2-11ea-8070-e2eb734c6f42.png)

**Comment by ta264** [comment]
Just to clarify, there are no plans to change how albums are shown in the UI - Lidarr will continue to show albums exclusively under the primary artist.

What I do plan to change is to allow lidarr to find files that are in the "wrong" artist folder, so that it can still match files that are filed under a joint artist folder.  This is in progress but need ls more testing.

**Comment by iAmRenzo** [comment]
> > And is there already a solution for this?
> > Because, the title "Out to Sea" isn't showing under Tom Misch alone nor Carmody. And there are a lot of these...
> 
> That is most probably because the release type in MB is set to 'Unspecified', which lidarr cannot import. The easiest way to rectify this is to edit the release on musicbrainz to 'Album' (or whatever it is), wait for an hour for the results to filter through to lidarr and then refresh and add the album.
> 
> ![image](https://user-images.githubusercontent.com/594700/70051807-2669ba00-15d2-11ea-8070-e2eb734c6f42.png)

It seems that it is easier for Lidarr to import these than to edit +50 releases on musicbrainz...

**Comment by ta264** [comment]
PRs welcome :)

**Comment by Cantello** [comment]
> It seems that it is easier for Lidarr to import these than to edit +50 releases on musicbrainz...

I see your point, but musicbrainz greatly profits from participation and if all apps that use MB's API are error-tolerant, then no errors will be fixed anymore.

**Comment by kimpenhaus** [comment]
![grafik](https://user-images.githubusercontent.com/575109/74319980-22030f80-4d80-11ea-82b8-ca421c08454a.png)

@ta264: can't agree that my original issue is fixed...

**Comment by ta264** [comment]
That's not a screenshot from nightly where it's fixed, that page is gone.

Its fixed in the sense lidarr doesn't care where the files are on disk. The albums will still show under the primary artist only and there are no immediate plans to change that.

**Comment by kimpenhaus** [comment]
@ta264 shame on me - you're right! thought i was on preview docker container already but must confess it was latest - since switching to preview the import screen is indeed gone. sorry for confusion.

**Comment by ta264** [comment]
No worries. Is it working as you hope now?

**Comment by kimpenhaus** [comment]
gna - have some other issues now :-) but that's a different story - synology is generating `@eadir` folders (for storing index informations and stuff) - those folders have some special permissions ... which is causing lidarr now to fail while scanning. will need to get a workaround for that... but it's not depending on the issue i had.

thanks for your work!
