### ISSUE TITLE
lidarr not currently working with ombi. Possible api issue?

### ISSUE THREAD

**Issue by gmhowell** [lidarr/Lidarr#818]
Attempting to open an artist's albums from Ombi 3.02456 does not work with Lidarr 0.6.2.883

Go to Ombi. Select 'Search' -> 'Music' -> 'Search Artist'
Enter artist name. Artist shows in list
Click 'View Albums'
No results returned.

**Expected behavior**
Album releases for the selected artist should be displayed.

**Screenshots**
This screen. Button at top right should display albums.

![image](https://user-images.githubusercontent.com/32222057/57999072-12c98c80-7aa2-11e9-9238-a4d9ecd54c1a.png)

**Logs**
Log output from immediately after 'View Albums' is clicked.

[lidarr.log](https://github.com/lidarr/Lidarr/files/3196458/lidarr.log)
**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System Debian Stretch
 - mono 5.20.1.19

**Comment by ta264** [comment]
That appears to be a very old version of ombi. You should probably upgrade first.

**Comment by ta264** [comment]
Bit you're right there does seem to be an issue with our metadata API. I'll take a look

**Comment by ta264** [comment]
Fixed

**Comment by gmhowell** [comment]
I don't think that's an old version of Ombi. Just checked https://github.com/tidusjar/Ombi/releases and 3.0.4256 is current release version.

Anyhow, thanks for taking a look.

**Comment by ta264** [comment]
Looking again you had a typo in your bug report that made it look old.  It should be working now.

**Comment by revelous** [comment]
I can't see what the fix was from your comment above. Is it included in the latest lidarr docker preview (version 0.6.2.898)? Ombi (version 3.0.4256) & Lidarr still don't play nice for me on that version.

**Comment by ta264** [comment]
The fix here was on our metadata feed and didnt require a client upgrade
